### ISSUE TITLE
Input Validation Error When Inputting String for side_ratio

### ISSUE THREAD

**Issue by MistrBones** [palant/image-resize-comfyui#2]
Hello, when using a node to input the value for side_ratio there is an input invalidation error that occurs. It looks like the parse_side_ratio() function is being called twice and the first call the value for side_ratio is empty. Unfortunately when the validation error is thrown this causes resize() to have no output even though parse_side_ratio() is called again with non-empty values.

I was able to hack around this problem by returning a default ratio from parse_side_ratio() when an exception occurs. The image then resizes according to the ratio input from my node and the default that I entered is ignored. I know this is not desirable behavior generally but it works for my use case. I took a crack at writing a proper fix but I can't make heads or tails of why side_ratio is empty on the first call to parse_side_ratio(). 

Also worth noting that this problem was completely bypassed when I entered the value for the side_ratio input via a primitive node.

Picture below shows a simplified example of a graph that will produce this issue.

![image](https://github.com/palant/image-resize-comfyui/assets/40408106/6cd534b7-5b94-4aab-833f-bdd1a2f52396)

**Comment by palant** [comment]
I can reproduce this issue. Primitive node compares differently, IMHO simply because it is client-side behavior – validation on the server side doesn’t see it, as far as validation is concerned the value is filled in. This Simple String node from cg-use-everywhere on the other hand is a server-side node, so its value isn’t known when validation runs.

The question is how this can be addressed short of not doing any validation whatsoever. I’ve checked the built-in validation methods of ComfyUI and they have the same issue. They simply don’t expect the scenario where the validated values would come from outside. So as thing stand now, validation in ComfyUI is fundamentally broken.

I’d still like to keep it, so that configuration mistakes surface earlier than when prompt execution gets to this node. But I guess this requires considering any empty inputs for primitive values inherently valid…

**Comment by palant** [comment]
This seems to do it: inputs are validated if possible, otherwise validation is repeated during execution (produces a better error message than simply allowing the code to error out).
